# Generated by Django 4.2.3 on 2023-08-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisment',
            table='advertisments',
        ),
    ]
